### ISSUE TITLE
malloc - error for object - incorrect checksum for freed object

### ISSUE THREAD

**Issue by mane** [zmap/zmap#250]
Hi there,

I've installed zmap on mac osx using "brew install zmap" but after few seconds since I run a scan, it throws an error using it through the ethernet connection with the following command:

"zmap -p 80 -o output.txt"

I was wondering if you came across to the following error before:

zmap(34683,0x1067b6000) malloc: *** error for object 0x7f9b2b800160: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

It all runs fine over the wifi but of course I cannot use my 1Gb internet connection.

Please let me know if you need more details.

Thank you.

**Comment by dadrian** [comment]
I have not seen this before. Would it be possible for you to post a core dump of the crash?

**Comment by mane** [comment]
@dadrian I'll be happy to do that but I need help as I have no idea how to do it please.

**Comment by dadrian** [comment]
http://stackoverflow.com/questions/17965/generate-a-core-dump-in-linux

It should create a file callled `core` in whatever directory you ran the program from.

**Comment by mane** [comment]
Thanks @dadrian 

I've uploaded the core dump into dropbox (it's 149MB compressed).

Please take a look at the dump an let me know if that is ok: https://www.dropbox.com/s/gm6ij1tsf7py7wq/core.dump.zip?dl=0

Thank you.

**Comment by dadrian** [comment]
Well, it very clearly crashed when processing a received packet. However, this is kind an old version of ZMap (despite being latest in brew). Could you try running the building latest version of ZMap on the master branch and see if you can reproduce?

**Comment by mane** [comment]
Thanks @dadrian 

I've tried "zmap 2.0.0-RC1" but the behaviour it's the same.

If you need, here is another core dump: https://www.dropbox.com/s/0sd4rg7prox96s1/core2.dump.zip?dl=0

Thanks again for your time, it's really appreciated.

**Comment by dadrian** [comment]
In the 2.0.0-RC1, can you try commenting out lines 280 and 281 in `send.c` (the call to `log_debug`). I still can't seem to reproduce on my machine, but I have a guess as to what's happening.

If that doesn't fix it, can you rebuild with debug symbols (rerun `cmake -DENABLE_DEVELOPMENT=ON`, then run `make`), and post that core dump? Dumps with debug symbols are much easier to debug.

**Comment by mane** [comment]
line 280: struct in_addr addr;
line 281: addr.s_addr = curr;

Do you want me to comment that out?

**Comment by dadrian** [comment]
Comment out

```
log_debug("send", "send_packet failed for %s. %s",
      inet_ntoa(addr), strerror(errno));
```

**Comment by mane** [comment]
I've tried to commenting out those lines but it didn't worked.

Then I've recompiled as you suggested and it throws me an error:

mane:machine > zmap$ sudo cmake -DENABLE_DEVELOPMENT=ON
Password:
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mane/hacking/zmap
mane:machine > zmap$ make
[  1%] Building C object src/CMakeFiles/zblacklist.dir/zblacklist.c.o
[  2%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/blacklist.c.o
[  4%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/constraint.c.o
[  5%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/logger.c.o
[  6%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/pbm.c.o
[  8%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/random.c.o
[  9%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/rijndael-alg-fst.c.o
[ 11%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/xalloc.c.o
[ 12%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/lockfd.c.o
[ 13%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/util.c.o
[ 15%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/queue.c.o
[ 16%] Building C object src/CMakeFiles/zblacklist.dir/__/lib/csv.c.o
Linking C executable zblacklist
[ 16%] Built target zblacklist
Scanning dependencies of target zmap
[ 18%] Building C object src/CMakeFiles/zmap.dir/aesrand.c.o
[ 19%] Building C object src/CMakeFiles/zmap.dir/cyclic.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/expression.c.o
[ 22%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
[ 23%] Building C object src/CMakeFiles/zmap.dir/filter.c.o
[ 25%] Building C object src/CMakeFiles/zmap.dir/get_gateway.c.o
[ 26%] Building C object src/CMakeFiles/zmap.dir/iterator.c.o
[ 27%] Building C object src/CMakeFiles/zmap.dir/monitor.c.o
[ 29%] Building C object src/CMakeFiles/zmap.dir/recv.c.o
[ 30%] Building C object src/CMakeFiles/zmap.dir/send.c.o
/Users/mane/hacking/zmap/src/send.c:282:8: error: invalid preprocessing directive
                                                #log_debug("send", "send_packet failed for %s. %s",
                                                 ^
/Users/mane/hacking/zmap/src/send.c:283:12: error: invalid preprocessing directive
                                                #                 inet_ntoa(addr), strerror(errno));
                                                                  ^
2 errors generated.
make[2]: *** [src/CMakeFiles/zmap.dir/send.c.o] Error 1
make[1]: *** [src/CMakeFiles/zmap.dir/all] Error 2
make: *** [all] Error 2

**Comment by dadrian** [comment]
The comment symbol in C is //, not #.

**Comment by mane** [comment]
Hi @dadrian 

Sorry, my bad.

I've tried to commented out using // but the problem still there, even after that I've tried to re-compile using:

cmake -DENABLE_DEVELOPMENT=ON
make

**Comment by svshearer** [comment]
Although my zmap command is different, I have the same issue issue on OS X. I am running map 1.2.1.

**Comment by mane** [comment]
Hi @svshearer 

What command do you run?

**Comment by svshearer** [comment]
I am running:

sudo zmap -p 443 -o -

I have used other parameters which results in the same error as well. 

Spencer


121.10.26.58
111.168.4.64
23.50.104.195
104.66.68.250
69.60.206.137
 0:04 0%; send: 1099756 330 Kp/s (275 Kp/s avg); recv: 128 42 p/s (31 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.01%
172.225.15.95
37.252.1.154
199.230.54.166
89.216.59.6
zmap(46554,0x10aea9000) malloc: *** error for object 0x7f83cac05060: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Bad:zgrab svshearer$ sudo zmap -p 443 -o -

**Comment by dadrian** [comment]
Neither of these commands are crashing on my system.

My suspicion is this has something to do with a failed packet send. However, it's unlikely I'll be able to debug anything unless someone can post a core dump from a build with debug symbols (e.g. built with -DENABLE_DEVELOPMENT=ON), ideally from latest master.

**Comment by svshearer** [comment]
Hi David,

I am happy to do this. I have done the following:

Mac OS: brew install cmake gmp gengetopt json-c byacc libdnet

I am not sure what the command is to build with debug on. I know you asked me to use -DENABLE_DEVELOPMENT=ON.

If you will give me the commands I will build zmap and then send to you the code dump.

Thanks,
Spencer

**Comment by svshearer** [comment]
I am issuing the command cmake zmap -DENABLE_DEVELOPMENT=ON

I receive the error does not appear to contain CMakeLists.txt.

I have tried zmap/1.2.1 still with the same error. 

I have also searched my mac and cannot find the CMakeLists.txt

Hopefully I can get this working so I can send you the core dump.

Spencer

**Comment by dadrian** [comment]
Sorry about the delay.

You'll need to clone the repository or download latest master some other way from Github. Github provides instructions on how to do this.

`git clone https://github.com/zmap/zmap`

 Then, inside of the directory containing the ZMap code, run

`cmake -DENABLE_DEVELOPMENT=ON .`
`make`

ZMap will be built inside the `src` directory, so you should be able to run `./src/zmap` as ZMap after it built.

**Comment by svshearer** [comment]
Thanks for the help, we are getting closer. This is what I see now. 

Bad:zmap svshearer$ cmake -DENABLE_DEVELOPMENT=ON
-- The C compiler identification is AppleClang 6.0.0.6000057
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
CMake Error at CMakeLists.txt:70 (message):
  Did not find libjson


-- Configuring incomplete, errors occurred!


Spencer

**Comment by dadrian** [comment]
You need to run `brew install json-c`. I'll update our documentation, it's out of date.

**Comment by svshearer** [comment]
Thanks for your continues help. I did “Brew install jason-c” with the error below. 

Spencer

Bad:GitHub svshearer$ brew install json-c
==> Downloading https://homebrew.bintray.com/bottles/json-c-0.12.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/json-c-0.12.yosemite.bottle.1.tar.gz
==> Pouring json-c-0.12.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/json-c/0.12: 25 files, 228K
Bad:GitHub svshearer$ ls
zmap
Bad:GitHub svshearer$ cd zmap
Bad:zmap svshearer$ ls
10gigE.md	CHANGELOG	INSTALL		README		examples	src
AUTHORS		CMakeLists.txt	LICENSE		conf		lib		test
Bad:zmap svshearer$ cmake -DENABLE_DEVELOPMENT=ON
-- The C compiler identification is AppleClang 6.0.0.6000057
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
CMake Error at CMakeLists.txt:70 (message):
  Did not find libjson


-- Configuring incomplete, errors occurred!
See also "/Users/svshearer/GitHub/zmap/CMakeFiles/CMakeOutput.log".

**Comment by svshearer** [comment]
Problem solved, I ran brew install pkgconfig

Spencer

**Comment by svshearer** [comment]
I am still not able to run make as describe above. the net.h file is not found.

**Comment by dadrian** [comment]
@svshearer I just pushed a fix for building on newer version of OS X that fixes the dnet.h problem.

Sorry for the ridiculous amounts of delay on this issue.

**Comment by svshearer** [comment]
Hi David,

Thanks very much for taking care of this. I will test this out tonight.

Take care,
Spencer

**Comment by mane** [comment]
Thanks @dadrian really appreciated.

Keep the good work up.

**Comment by darksheer** [comment]
Running version 2.1.1 from brew, still getting the same issue:

```
$ sudo zmap -p 9200
Jul 31 18:07:07.182 [INFO] zmap: output module: csv
Jul 31 18:07:07.183 [INFO] csv: no output file selected, will use stdout
 0:00 0%; send: 691 0 p/s (398 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 284548 284 Kp/s (284 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
118.149.59.232
223.164.15.45
 0:02 0%; send: 579161 294 Kp/s (289 Kp/s avg); recv: 2 1 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
115.47.46.150
199.235.26.211
43.242.44.84
186.120.55.122
59.184.39.220
 0:03 0%; send: 886937 308 Kp/s (295 Kp/s avg); recv: 7 4 p/s (2 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
45.248.69.103
199.197.119.26
 0:04 0%; send: 1176911 290 Kp/s (294 Kp/s avg); recv: 9 1 p/s (2 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
46.174.53.161
170.104.186.40
144.89.10.20
158.123.67.72
118.230.26.7
 0:05 0% (3h30m left); send: 1464532 288 Kp/s (293 Kp/s avg); recv: 14 4 p/s (2 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
144.89.19.205
136.227.2.44
188.92.33.247
211.233.53.154
206.253.80.31
 0:06 0% (3h31m left); send: 1747959 283 Kp/s (291 Kp/s avg); recv: 19 4 p/s (3 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
159.238.131.84
zmap(3342,0x700000310000) malloc: *** error for object 0x7f8ecc800460: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

**Comment by zakird** [comment]
@darksheer This should be fixed in master but was not in place before 2.1.1 was released. Can you please see if this happens for you in master?

**Comment by nixawk** [comment]
I have the same problem with **zmap** from brew source. Please compile **zmap** yourself, and the problem can be solved.

```
$ brew install cmake gmp gengetopt json-c byacc libdnet libunistring
$ cmake -DENABLE_DEVELOPMENT=OFF .
$ make
```

**Comment by dadrian** [comment]
`brew install --HEAD zmap` I assume also works.
